apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: x4-finconfig
  namespace: x4-s24
  name: x4-finconfig-configmap
data:
  application.properties: |
    spring.profiles.active=development
    spring.datasource.url=jdbc:mysql://mysql-service:3306/x4_finconfig?useLegacyDatetimeCode=false&serverTimezone=UTC
    spring.datasource.username=${mysql-user}
    spring.datasource.password=${mysql-password}
    spring.activemq.broker-url=tcp://activemq-service:61616
    spring.activemq.username=${activemq-user}
    spring.activemq.password=${activemq-password}
    spring.redis.url=redis-service
    spring.redis.port=6379
    spring.config.use-legacy-processing=true
    server.port=8080
    server.servlet.contextpath=/
    feign.task-service=http://x4-task-service:8080/
    jwt.signing-key=${jwt-signing-key}
    management.endpoints.web.exposure.include=health,info
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: x4-finconfig
  name: x4-finconfig-service
  namespace: x4-s24
spec:
  type: NodePort
  selector:
    app: x4-finconfig
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x4-finconfig
  namespace: x4-s24
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: x4-finconfig
  template:
    metadata:
      labels:
        app: x4-finconfig
        log-format: json
    spec:
      priorityClassName: medium-priority
      containers:
      - name: x4-finconfig
        image: pkg.asyx.com:5000/asyx/x4-finconfig-application:4.4.11-455
        imagePullPolicy: Always
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: mysql-user
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-asyx-user
        - name: mysql-password
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key:  mysql-asyx-password 
        - name: jwt-signing-key
          valueFrom:
            secretKeyRef:
              name: jwt-signing-key-secret
              key: secret
        - name: activemq-user
          valueFrom:
            secretKeyRef:
              name: activemq-secret
              key: activemq-user
        - name: activemq-password
          valueFrom:
            secretKeyRef:
              name: activemq-secret
              key: activemq-password
        volumeMounts:
        - name: x4-finconfig-config
          mountPath: /x4/config/application.properties
          subPath: application.properties
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 60
      imagePullSecrets:
      - name: asyx-docker-prod-secret
      volumes:
      - name: x4-finconfig-config
        configMap:
          name: x4-finconfig-configmap